# Generated by Django 3.2.19 on 2023-05-20 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kodukai', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Valid_date',
            new_name='ValidDate',
        ),
    ]
