# Generated by Django 3.2.19 on 2023-05-21 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kodukai', '0003_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
