# Generated by Django 3.2.19 on 2023-05-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodukai', '0004_delete_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurer',
            name='use_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='validdate',
            name='valid_date',
            field=models.DateField(),
        ),
    ]
