# Generated by Django 3.2.19 on 2023-05-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodukai', '0006_alter_kanjo_kanjo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanjo',
            name='kanjo',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='treasurer',
            name='credit',
            field=models.CharField(choices=[('b', '銀行'), ('c', 'カード'), ('g', '現金'), ('d', '借金'), ('s', 'スイカ'), ('k', '費用、収入'), ('t', '立替'), ('d', '引当金'), ('p', 'ペイペイ')], max_length=1, verbose_name='勘定'),
        ),
        migrations.AlterField(
            model_name='treasurer',
            name='debit',
            field=models.CharField(choices=[('b', '銀行'), ('c', 'カード'), ('g', '現金'), ('d', '借金'), ('s', 'スイカ'), ('k', '費用、収入'), ('t', '立替'), ('d', '引当金'), ('p', 'ペイペイ')], max_length=1, verbose_name='勘定'),
        ),
    ]
