# Generated by Django 3.2.19 on 2023-05-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodukai', '0007_auto_20230527_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurer',
            name='item',
            field=models.CharField(choices=[('雑収', '雑収'), ('雑費', '雑費'), ('買い物', '買い物'), ('飲食', '飲食'), ('食費', '食費'), ('入金', '入金'), ('出金', '出金'), ('交通費', '交通費'), ('カード引落', 'カード引落'), ('振込', '振込'), ('立替', '立替')], max_length=20, verbose_name='アイテム'),
        ),
    ]
