# Generated by Django 3.2.19 on 2023-06-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodukai', '0009_auto_20230530_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurer',
            name='credit',
            field=models.CharField(choices=[('b', '銀行'), ('c', 'カード'), ('g', '現金'), ('d', '借金'), ('s', 'スイカ'), ('k', '収入'), ('t', '立替'), ('d', '引当金'), ('p', 'ペイペイ'), ('z', 'ダミー')], max_length=1, verbose_name='勘定'),
        ),
        migrations.AlterField(
            model_name='treasurer',
            name='debit',
            field=models.CharField(choices=[('b', '銀行'), ('c', 'カード'), ('g', '現金'), ('d', '借金'), ('s', 'スイカ'), ('k', '費用'), ('t', '立替'), ('d', '引当金'), ('p', 'ペイペイ'), ('z', 'ダミー')], max_length=1, verbose_name='勘定'),
        ),
        migrations.AlterField(
            model_name='treasurer',
            name='item',
            field=models.CharField(choices=[('雑収', '雑収'), ('雑費', '雑費'), ('買い物', '買い物'), ('飲食', '飲食'), ('食費', '食費'), ('入金', '入金'), ('出金', '出金'), ('交通費', '交通費'), ('カード引落', 'カード引落'), ('振込', '振込'), ('立替', '立替'), ('繰越', '繰越')], max_length=20, verbose_name='アイテム'),
        ),
    ]
