# Generated by Django 3.2.19 on 2023-06-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodukai', '0010_auto_20230602_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='validdate',
            name='key',
            field=models.IntegerField(default=1),
        ),
    ]
