# Generated by Django 3.2.19 on 2023-06-03 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodukai', '0012_kanjocredit_kanjodebit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurer',
            name='credit',
            field=models.CharField(choices=[('b', '銀行'), ('c', 'カード'), ('g', '現金'), ('d', '借金'), ('s', 'スイカ'), ('k', '収入'), ('t', '立替'), ('d', '引当金'), ('p', 'ペイペイ'), ('z', 'ダミー')], max_length=20, verbose_name='勘定'),
        ),
        migrations.AlterField(
            model_name='treasurer',
            name='debit',
            field=models.CharField(choices=[('b', '銀行'), ('c', 'カード'), ('g', '現金'), ('d', '借金'), ('s', 'スイカ'), ('k', '費用'), ('t', '立替'), ('d', '引当金'), ('p', 'ペイペイ'), ('z', 'ダミー')], max_length=20, verbose_name='勘定'),
        ),
    ]
