# Generated by Django 3.2.19 on 2023-06-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodukai', '0014_auto_20230603_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurer',
            name='user',
            field=models.CharField(default='hei@test.com', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='validdate',
            name='user',
            field=models.CharField(default='hei@test.com', max_length=150),
            preserve_default=False,
        ),
    ]
