# Generated by Django 3.2.19 on 2023-06-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodukai', '0015_auto_20230604_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurer',
            name='credit',
            field=models.CharField(choices=[('銀行', '銀行'), ('カード', 'カード'), ('現金', '現金'), ('借金', '借金'), ('スイカ', 'スイカ'), ('収入', '収入'), ('立替', '立替'), ('引当金', '引当金'), ('ペイペイ', 'ペイペイ'), ('ダミー', 'ダミー')], max_length=20, verbose_name='勘定'),
        ),
    ]
